INSERT INTO estado(Nome, UF) VALUES ('MATO GROSSO DO SUL', 'MS');
INSERT INTO estado(Nome, UF) VALUES('MATO GROSSO', 'MT');
INSERT INTO estado(Nome, UF) VALUES('SÃO PAULO', 'SP');
INSERT INTO estado(Nome, UF) VALUES('MINAS GERAIS', 'MG');
INSERT INTO estado(Nome, UF) VALUES('BAHIA', 'BA');
INSERT INTO estado(Nome, UF) VALUES('CEARÁ', 'CE'); 
INSERT INTO estado(Nome, UF) VALUES('AMAPÁ', 'AP');
INSERT INTO estado(Nome, UF) VALUES('AMAZONAS', 'AM');
INSERT INTO estado(Nome, UF) VALUES('RIO DE JANEIRO', 'RJ');
INSERT INTO estado(Nome, UF) VALUES('SANTA CATARINA','SC')